title = "Configure Arch Linux(btw)"
description = "Configure your Arch Linux system with ease using Mozkit's intuitive interface. Customize settings, manage packages, and optimize performance effortlessly."

[[action]]
description = "Say Arch BTW"
tool = "bash"
arguments = ['for i in {1..100}; do echo "I use Arch"; done']

[[action]]
description = "Say Arch BTW"
tool = "bash"
arguments = ['printf "I use Arch\n%.0s" {1..100}']
