title = "Configure Arch Linux(btw) 2"
description = "Configure your Arch Linux system with ease using Mozkit's intuitive interface. Customize settings, manage packages, and optimize performance effortlessly."

[[action]]
description = "Say Arch BTW"
tool = "echo"
arguments = ["Arch BTW"]

[[action]]
description = "What is the best linux distro ever released?"
tool = "ask"
arguments = ["var=best_distro"]
