title = "Configure Arch Linux(btw)"
description = "Configure your Arch Linux system with ease using Mozkit's intuitive interface. Customize settings, manage packages, and optimize performance effortlessly."

[[action]]
description = "Say Arch BTW"
tool = "bash"
arguments = ["echo Arch BTW"]

[[action]]
description = "Say Arch Linux is the best distro ever"
tool = "bash"
arguments = ["echo Arch Linux is the best distro ever"]
